services:
  jupyter:
    build:
      context: .
    volumes:
      - .:/workdir
    ports:
      - "8888:8888"
    command: jupyter notebook --allow-root --no-browser --port=8888 --ip=0.0.0.0
    tty: true
